runner:
  rubocop:
    cmd: bundle exec rubocop
#  brakeman:
#    cmd: bundle exec brakeman --quiet --format tabs
# too many warnings which is not important.
#  reek:
#    cmd: bundle exec reek --single-line
  haml-lint:
    cmd: bundle exec haml-lint
#  eslint:
#    cmd: yarn run eslint app/**/*.js
#  stylelint:
#    cmd: yarn run stylelint app/**/*.{css,scss}
  grep-testpdf:
    cmd: grep -r "TestPdf" app || true
    format: "%f:%l:%m"
    level: error
    message: "'TestPdf' should not exist in the codebase."

