runner:
  rubocop:
    cmd: bundle exec rubocop
#  brakeman:
#    cmd: bundle exec brakeman --quiet --format tabs
# too many warnings which is not important.
#  reek:
#    cmd: bundle exec reek --single-line
  haml-lint:
    cmd: bundle exec haml-lint
#  eslint:
#    cmd: yarn run eslint app/**/*.js
#  stylelint:
#    cmd: yarn run stylelint app/**/*.{css,scss}
  grep-testpdf:
    grep -n -r "TestPdf" app | awk -F: '{print $1 ":" $2 ":" $3}'


