name: code_analysis
on: [pull_request]
jobs:
  code_analysis:
    name: runner
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: cache vendor/bundle
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: bundle install
        run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      - name: yarn install
        run: yarn install
      - name: install reviewdog
        uses: reviewdog/action-setup@v1
      - name: Check for 'TestPdf' occurrences
        run: |
          mkdir -p reviewdog-report
          grep -r --line-number "TestPdf" app > reviewdog-report/testpdf.log || true
      - name: reviewdog
        run: reviewdog -reporter=github-pr-check
