name: rspec
on: [push]

jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3:
