name: rspec
on: [push]

jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        id: buildx
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}
            refs/head/main
      - name: Cache Composer layers
        uses: actions/cache@v4
        with:
          path: /tmp/.composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('Gemfile.lock') }}
            ${{ runner.os }}-composer-
